export * from '../pages/Home/Home';
export * from './Header/Header';
export * from './Footer/Footer';
export * from './MoviesList/MovieList';
export * from './MoviesListCard/MovieListCard';
export * from './MoviesDetails/MoviesDetails';
export * from './MovieDetails/MovieDetails';
export * from './Genres/Genres';
export * from './Genre/Genre';
