export * from '../pages/Home/Home';
export * from './Header/Header';
export * from './Footer/Footer';
export * from './MoviesList/MovieList';
export * from './MoviesListCard/MovieListCard';
export * from './GenreMovies/GenreMovies';
export * from './GenreMovie/GenreMovie';
export * from './MoviesDetails/MoviesDetails';
export * from './MovieDetails/MovieDetails';
